apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frontend

secretGenerator:
  - name: regcred
    type: kubernetes.io/dockerconfigjson
    files:
      - ".dockerconfigjson"

resources:
  - ingress.yml
  - web.yml
