// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
extension Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    public enum Schemas {
        /// - Remark: Generated from `#/components/schemas/BlobInfo`.
        public struct BlobInfo: Codable, Hashable, Sendable {
            /// Content identifier of the blob, never the file identity or record revision.
            ///
            /// - Remark: Generated from `#/components/schemas/BlobInfo/cid`.
            public var cid: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlobInfo/mimeType`.
            public var mimeType: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlobInfo/size`.
            public var size: Swift.Int64
            /// Creates a new `BlobInfo`.
            ///
            /// - Parameters:
            ///   - cid: Content identifier of the blob, never the file identity or record revision.
            ///   - mimeType:
            ///   - size:
            public init(
                cid: Swift.String,
                mimeType: Swift.String,
                size: Swift.Int64
            ) {
                self.cid = cid
                self.mimeType = mimeType
                self.size = size
            }
            public enum CodingKeys: String, CodingKey {
                case cid
                case mimeType
                case size
            }
        }
        /// - Remark: Generated from `#/components/schemas/CreateFile`.
        public struct CreateFile: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/CreateFile/name`.
            public var name: Swift.String
            /// - Remark: Generated from `#/components/schemas/CreateFile/parentId`.
            public var parentId: Swift.String?
            /// - Remark: Generated from `#/components/schemas/CreateFile/kind`.
            public var kind: Components.Schemas.FileKind
            /// Creates a new `CreateFile`.
            ///
            /// - Parameters:
            ///   - name:
            ///   - parentId:
            ///   - kind:
            public init(
                name: Swift.String,
                parentId: Swift.String? = nil,
                kind: Components.Schemas.FileKind
            ) {
                self.name = name
                self.parentId = parentId
                self.kind = kind
            }
            public enum CodingKeys: String, CodingKey {
                case name
                case parentId
                case kind
            }
        }
        /// - Remark: Generated from `#/components/schemas/DuplicateFile`.
        public struct DuplicateFile: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/DuplicateFile/revision`.
            public var revision: Swift.String
            /// - Remark: Generated from `#/components/schemas/DuplicateFile/name`.
            public var name: Swift.String
            /// - Remark: Generated from `#/components/schemas/DuplicateFile/parentId`.
            public var parentId: Swift.String?
            /// Creates a new `DuplicateFile`.
            ///
            /// - Parameters:
            ///   - revision:
            ///   - name:
            ///   - parentId:
            public init(
                revision: Swift.String,
                name: Swift.String,
                parentId: Swift.String? = nil
            ) {
                self.revision = revision
                self.name = name
                self.parentId = parentId
            }
            public enum CodingKeys: String, CodingKey {
                case revision
                case name
                case parentId
            }
        }
        /// - Remark: Generated from `#/components/schemas/ErrorBody`.
        public struct ErrorBody: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/ErrorBody/code`.
            public var code: Swift.String
            /// - Remark: Generated from `#/components/schemas/ErrorBody/message`.
            public var message: Swift.String
            /// Creates a new `ErrorBody`.
            ///
            /// - Parameters:
            ///   - code:
            ///   - message:
            public init(
                code: Swift.String,
                message: Swift.String
            ) {
                self.code = code
                self.message = message
            }
            public enum CodingKeys: String, CodingKey {
                case code
                case message
            }
        }
        /// - Remark: Generated from `#/components/schemas/FileEntry`.
        public struct FileEntry: Codable, Hashable, Sendable {
            /// Stable record key within the authenticated account's drive space.
            ///
            /// - Remark: Generated from `#/components/schemas/FileEntry/id`.
            public var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/FileEntry/uri`.
            public var uri: Swift.String
            /// Current record CID, used to reject stale writes.
            ///
            /// - Remark: Generated from `#/components/schemas/FileEntry/revision`.
            public var revision: Swift.String
            /// Omitted for a root-level entry.
            ///
            /// - Remark: Generated from `#/components/schemas/FileEntry/parentId`.
            public var parentId: Swift.String?
            /// - Remark: Generated from `#/components/schemas/FileEntry/name`.
            public var name: Swift.String
            /// - Remark: Generated from `#/components/schemas/FileEntry/kind`.
            public var kind: Components.Schemas.FileKind
            /// - Remark: Generated from `#/components/schemas/FileEntry/createdAt`.
            public var createdAt: Swift.String
            /// - Remark: Generated from `#/components/schemas/FileEntry/updatedAt`.
            public var updatedAt: Swift.String
            /// - Remark: Generated from `#/components/schemas/FileEntry/trashedAt`.
            public var trashedAt: Swift.String?
            /// - Remark: Generated from `#/components/schemas/FileEntry/size`.
            public var size: Swift.Int64
            /// - Remark: Generated from `#/components/schemas/FileEntry/blob`.
            public var blob: Components.Schemas.BlobInfo?
            /// Creates a new `FileEntry`.
            ///
            /// - Parameters:
            ///   - id: Stable record key within the authenticated account's drive space.
            ///   - uri:
            ///   - revision: Current record CID, used to reject stale writes.
            ///   - parentId: Omitted for a root-level entry.
            ///   - name:
            ///   - kind:
            ///   - createdAt:
            ///   - updatedAt:
            ///   - trashedAt:
            ///   - size:
            ///   - blob:
            public init(
                id: Swift.String,
                uri: Swift.String,
                revision: Swift.String,
                parentId: Swift.String? = nil,
                name: Swift.String,
                kind: Components.Schemas.FileKind,
                createdAt: Swift.String,
                updatedAt: Swift.String,
                trashedAt: Swift.String? = nil,
                size: Swift.Int64,
                blob: Components.Schemas.BlobInfo? = nil
            ) {
                self.id = id
                self.uri = uri
                self.revision = revision
                self.parentId = parentId
                self.name = name
                self.kind = kind
                self.createdAt = createdAt
                self.updatedAt = updatedAt
                self.trashedAt = trashedAt
                self.size = size
                self.blob = blob
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case uri
                case revision
                case parentId
                case name
                case kind
                case createdAt
                case updatedAt
                case trashedAt
                case size
                case blob
            }
        }
        /// - Remark: Generated from `#/components/schemas/FileKind`.
        @frozen public enum FileKind: String, Codable, Hashable, Sendable, CaseIterable {
            case file = "file"
            case directory = "directory"
        }
        /// - Remark: Generated from `#/components/schemas/FileList`.
        public struct FileList: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/FileList/files`.
            public var files: [Components.Schemas.FileEntry]
            /// Creates a new `FileList`.
            ///
            /// - Parameters:
            ///   - files:
            public init(files: [Components.Schemas.FileEntry]) {
                self.files = files
            }
            public enum CodingKeys: String, CodingKey {
                case files
            }
        }
        /// - Remark: Generated from `#/components/schemas/FileVersion`.
        public struct FileVersion: Codable, Hashable, Sendable {
            /// Immutable version record key, distinct from the file's stable ID.
            ///
            /// - Remark: Generated from `#/components/schemas/FileVersion/id`.
            public var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/FileVersion/fileId`.
            public var fileId: Swift.String
            /// - Remark: Generated from `#/components/schemas/FileVersion/capturedAt`.
            public var capturedAt: Swift.String
            /// - Remark: Generated from `#/components/schemas/FileVersion/file`.
            public var file: Components.Schemas.FileEntry
            /// Creates a new `FileVersion`.
            ///
            /// - Parameters:
            ///   - id: Immutable version record key, distinct from the file's stable ID.
            ///   - fileId:
            ///   - capturedAt:
            ///   - file:
            public init(
                id: Swift.String,
                fileId: Swift.String,
                capturedAt: Swift.String,
                file: Components.Schemas.FileEntry
            ) {
                self.id = id
                self.fileId = fileId
                self.capturedAt = capturedAt
                self.file = file
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case fileId
                case capturedAt
                case file
            }
        }
        /// - Remark: Generated from `#/components/schemas/LoginInput`.
        public struct LoginInput: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/LoginInput/handle`.
            public var handle: Swift.String
            /// Creates a new `LoginInput`.
            ///
            /// - Parameters:
            ///   - handle:
            public init(handle: Swift.String) {
                self.handle = handle
            }
            public enum CodingKeys: String, CodingKey {
                case handle
            }
        }
        /// - Remark: Generated from `#/components/schemas/LoginOutput`.
        public struct LoginOutput: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/LoginOutput/redirectUrl`.
            public var redirectUrl: Swift.String
            /// Creates a new `LoginOutput`.
            ///
            /// - Parameters:
            ///   - redirectUrl:
            public init(redirectUrl: Swift.String) {
                self.redirectUrl = redirectUrl
            }
            public enum CodingKeys: String, CodingKey {
                case redirectUrl
            }
        }
        /// - Remark: Generated from `#/components/schemas/RevisionInput`.
        public struct RevisionInput: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/RevisionInput/revision`.
            public var revision: Swift.String
            /// Creates a new `RevisionInput`.
            ///
            /// - Parameters:
            ///   - revision:
            public init(revision: Swift.String) {
                self.revision = revision
            }
            public enum CodingKeys: String, CodingKey {
                case revision
            }
        }
        /// - Remark: Generated from `#/components/schemas/Session`.
        public struct Session: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/Session/user`.
            public var user: Components.Schemas.User
            /// - Remark: Generated from `#/components/schemas/Session/space`.
            public var space: Components.Schemas.Space
            /// Creates a new `Session`.
            ///
            /// - Parameters:
            ///   - user:
            ///   - space:
            public init(
                user: Components.Schemas.User,
                space: Components.Schemas.Space
            ) {
                self.user = user
                self.space = space
            }
            public enum CodingKeys: String, CodingKey {
                case user
                case space
            }
        }
        /// - Remark: Generated from `#/components/schemas/Space`.
        public struct Space: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/Space/uri`.
            public var uri: Swift.String
            /// - Remark: Generated from `#/components/schemas/Space/authorityDid`.
            public var authorityDid: Swift.String
            /// - Remark: Generated from `#/components/schemas/Space/type`.
            public var _type: Swift.String
            /// - Remark: Generated from `#/components/schemas/Space/key`.
            public var key: Swift.String
            /// Creates a new `Space`.
            ///
            /// - Parameters:
            ///   - uri:
            ///   - authorityDid:
            ///   - _type:
            ///   - key:
            public init(
                uri: Swift.String,
                authorityDid: Swift.String,
                _type: Swift.String,
                key: Swift.String
            ) {
                self.uri = uri
                self.authorityDid = authorityDid
                self._type = _type
                self.key = key
            }
            public enum CodingKeys: String, CodingKey {
                case uri
                case authorityDid
                case _type = "type"
                case key
            }
        }
        /// Renames a file without changing its parent or stable identity.
        ///
        /// - Remark: Generated from `#/components/schemas/UpdateFile`.
        public struct UpdateFile: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/UpdateFile/revision`.
            public var revision: Swift.String
            /// - Remark: Generated from `#/components/schemas/UpdateFile/name`.
            public var name: Swift.String
            /// Creates a new `UpdateFile`.
            ///
            /// - Parameters:
            ///   - revision:
            ///   - name:
            public init(
                revision: Swift.String,
                name: Swift.String
            ) {
                self.revision = revision
                self.name = name
            }
            public enum CodingKeys: String, CodingKey {
                case revision
                case name
            }
        }
        /// - Remark: Generated from `#/components/schemas/User`.
        public struct User: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/User/did`.
            public var did: Swift.String
            /// - Remark: Generated from `#/components/schemas/User/handle`.
            public var handle: Swift.String
            /// Creates a new `User`.
            ///
            /// - Parameters:
            ///   - did:
            ///   - handle:
            public init(
                did: Swift.String,
                handle: Swift.String
            ) {
                self.did = did
                self.handle = handle
            }
            public enum CodingKeys: String, CodingKey {
                case did
                case handle
            }
        }
        /// - Remark: Generated from `#/components/schemas/VersionList`.
        public struct VersionList: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/VersionList/versions`.
            public var versions: [Components.Schemas.FileVersion]
            /// Creates a new `VersionList`.
            ///
            /// - Parameters:
            ///   - versions:
            public init(versions: [Components.Schemas.FileVersion]) {
                self.versions = versions
            }
            public enum CodingKeys: String, CodingKey {
                case versions
            }
        }
    }
}
