// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
public protocol APIProtocol: Sendable {
    /// - Remark: HTTP `POST /oauth/login`.
    /// - Remark: Generated from `#/paths//oauth/login/post(login)`.
    func login(_ input: Operations.login.Input) async throws -> Operations.login.Output
    /// - Remark: HTTP `GET /api/v1/session`.
    /// - Remark: Generated from `#/paths//api/v1/session/get(session)`.
    func session(_ input: Operations.session.Input) async throws -> Operations.session.Output
    /// - Remark: HTTP `POST /api/v1/logout`.
    /// - Remark: Generated from `#/paths//api/v1/logout/post(logout)`.
    func logout(_ input: Operations.logout.Input) async throws -> Operations.logout.Output
    /// - Remark: HTTP `GET /api/v1/files`.
    /// - Remark: Generated from `#/paths//api/v1/files/get(listFiles)`.
    func listFiles(_ input: Operations.listFiles.Input) async throws -> Operations.listFiles.Output
    /// - Remark: HTTP `POST /api/v1/files`.
    /// - Remark: Generated from `#/paths//api/v1/files/post(createFile)`.
    func createFile(_ input: Operations.createFile.Input) async throws -> Operations.createFile.Output
    /// - Remark: HTTP `GET /api/v1/files/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/files/{id}/get(getFile)`.
    func getFile(_ input: Operations.getFile.Input) async throws -> Operations.getFile.Output
    /// - Remark: HTTP `PUT /api/v1/files/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/files/{id}/put(updateFile)`.
    func updateFile(_ input: Operations.updateFile.Input) async throws -> Operations.updateFile.Output
    /// - Remark: HTTP `POST /api/v1/files/{id}/duplicate`.
    /// - Remark: Generated from `#/paths//api/v1/files/{id}/duplicate/post(duplicateFile)`.
    func duplicateFile(_ input: Operations.duplicateFile.Input) async throws -> Operations.duplicateFile.Output
    /// - Remark: HTTP `POST /api/v1/files/{id}/trash`.
    /// - Remark: Generated from `#/paths//api/v1/files/{id}/trash/post(trashFile)`.
    func trashFile(_ input: Operations.trashFile.Input) async throws -> Operations.trashFile.Output
    /// - Remark: HTTP `POST /api/v1/files/{id}/restore`.
    /// - Remark: Generated from `#/paths//api/v1/files/{id}/restore/post(restoreFile)`.
    func restoreFile(_ input: Operations.restoreFile.Input) async throws -> Operations.restoreFile.Output
    /// - Remark: HTTP `GET /api/v1/files/{id}/versions`.
    /// - Remark: Generated from `#/paths//api/v1/files/{id}/versions/get(listVersions)`.
    func listVersions(_ input: Operations.listVersions.Input) async throws -> Operations.listVersions.Output
    /// - Remark: HTTP `POST /api/v1/files/{id}/versions/{versionId}/restore`.
    /// - Remark: Generated from `#/paths//api/v1/files/{id}/versions/{versionId}/restore/post(restoreVersion)`.
    func restoreVersion(_ input: Operations.restoreVersion.Input) async throws -> Operations.restoreVersion.Output
    /// - Remark: HTTP `POST /api/v1/files/upload`.
    /// - Remark: Generated from `#/paths//api/v1/files/upload/post(uploadFile)`.
    func uploadFile(_ input: Operations.uploadFile.Input) async throws -> Operations.uploadFile.Output
    /// - Remark: HTTP `GET /api/v1/files/{id}/content`.
    /// - Remark: Generated from `#/paths//api/v1/files/{id}/content/get(downloadFile)`.
    func downloadFile(_ input: Operations.downloadFile.Input) async throws -> Operations.downloadFile.Output
    /// - Remark: HTTP `PUT /api/v1/files/{id}/content`.
    /// - Remark: Generated from `#/paths//api/v1/files/{id}/content/put(replaceContent)`.
    func replaceContent(_ input: Operations.replaceContent.Input) async throws -> Operations.replaceContent.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// - Remark: HTTP `POST /oauth/login`.
    /// - Remark: Generated from `#/paths//oauth/login/post(login)`.
    public func login(
        headers: Operations.login.Input.Headers = .init(),
        body: Operations.login.Input.Body
    ) async throws -> Operations.login.Output {
        try await login(Operations.login.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /api/v1/session`.
    /// - Remark: Generated from `#/paths//api/v1/session/get(session)`.
    public func session(headers: Operations.session.Input.Headers = .init()) async throws -> Operations.session.Output {
        try await session(Operations.session.Input(headers: headers))
    }
    /// - Remark: HTTP `POST /api/v1/logout`.
    /// - Remark: Generated from `#/paths//api/v1/logout/post(logout)`.
    public func logout(headers: Operations.logout.Input.Headers = .init()) async throws -> Operations.logout.Output {
        try await logout(Operations.logout.Input(headers: headers))
    }
    /// - Remark: HTTP `GET /api/v1/files`.
    /// - Remark: Generated from `#/paths//api/v1/files/get(listFiles)`.
    public func listFiles(
        query: Operations.listFiles.Input.Query = .init(),
        headers: Operations.listFiles.Input.Headers = .init()
    ) async throws -> Operations.listFiles.Output {
        try await listFiles(Operations.listFiles.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /api/v1/files`.
    /// - Remark: Generated from `#/paths//api/v1/files/post(createFile)`.
    public func createFile(
        headers: Operations.createFile.Input.Headers = .init(),
        body: Operations.createFile.Input.Body
    ) async throws -> Operations.createFile.Output {
        try await createFile(Operations.createFile.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /api/v1/files/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/files/{id}/get(getFile)`.
    public func getFile(
        path: Operations.getFile.Input.Path,
        headers: Operations.getFile.Input.Headers = .init()
    ) async throws -> Operations.getFile.Output {
        try await getFile(Operations.getFile.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `PUT /api/v1/files/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/files/{id}/put(updateFile)`.
    public func updateFile(
        path: Operations.updateFile.Input.Path,
        headers: Operations.updateFile.Input.Headers = .init(),
        body: Operations.updateFile.Input.Body
    ) async throws -> Operations.updateFile.Output {
        try await updateFile(Operations.updateFile.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /api/v1/files/{id}/duplicate`.
    /// - Remark: Generated from `#/paths//api/v1/files/{id}/duplicate/post(duplicateFile)`.
    public func duplicateFile(
        path: Operations.duplicateFile.Input.Path,
        headers: Operations.duplicateFile.Input.Headers = .init(),
        body: Operations.duplicateFile.Input.Body
    ) async throws -> Operations.duplicateFile.Output {
        try await duplicateFile(Operations.duplicateFile.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /api/v1/files/{id}/trash`.
    /// - Remark: Generated from `#/paths//api/v1/files/{id}/trash/post(trashFile)`.
    public func trashFile(
        path: Operations.trashFile.Input.Path,
        headers: Operations.trashFile.Input.Headers = .init(),
        body: Operations.trashFile.Input.Body
    ) async throws -> Operations.trashFile.Output {
        try await trashFile(Operations.trashFile.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /api/v1/files/{id}/restore`.
    /// - Remark: Generated from `#/paths//api/v1/files/{id}/restore/post(restoreFile)`.
    public func restoreFile(
        path: Operations.restoreFile.Input.Path,
        headers: Operations.restoreFile.Input.Headers = .init(),
        body: Operations.restoreFile.Input.Body
    ) async throws -> Operations.restoreFile.Output {
        try await restoreFile(Operations.restoreFile.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /api/v1/files/{id}/versions`.
    /// - Remark: Generated from `#/paths//api/v1/files/{id}/versions/get(listVersions)`.
    public func listVersions(
        path: Operations.listVersions.Input.Path,
        headers: Operations.listVersions.Input.Headers = .init()
    ) async throws -> Operations.listVersions.Output {
        try await listVersions(Operations.listVersions.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /api/v1/files/{id}/versions/{versionId}/restore`.
    /// - Remark: Generated from `#/paths//api/v1/files/{id}/versions/{versionId}/restore/post(restoreVersion)`.
    public func restoreVersion(
        path: Operations.restoreVersion.Input.Path,
        headers: Operations.restoreVersion.Input.Headers = .init(),
        body: Operations.restoreVersion.Input.Body
    ) async throws -> Operations.restoreVersion.Output {
        try await restoreVersion(Operations.restoreVersion.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /api/v1/files/upload`.
    /// - Remark: Generated from `#/paths//api/v1/files/upload/post(uploadFile)`.
    public func uploadFile(
        query: Operations.uploadFile.Input.Query,
        headers: Operations.uploadFile.Input.Headers = .init(),
        body: Operations.uploadFile.Input.Body
    ) async throws -> Operations.uploadFile.Output {
        try await uploadFile(Operations.uploadFile.Input(
            query: query,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /api/v1/files/{id}/content`.
    /// - Remark: Generated from `#/paths//api/v1/files/{id}/content/get(downloadFile)`.
    public func downloadFile(
        path: Operations.downloadFile.Input.Path,
        headers: Operations.downloadFile.Input.Headers = .init()
    ) async throws -> Operations.downloadFile.Output {
        try await downloadFile(Operations.downloadFile.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `PUT /api/v1/files/{id}/content`.
    /// - Remark: Generated from `#/paths//api/v1/files/{id}/content/put(replaceContent)`.
    public func replaceContent(
        path: Operations.replaceContent.Input.Path,
        query: Operations.replaceContent.Input.Query,
        headers: Operations.replaceContent.Input.Headers = .init(),
        body: Operations.replaceContent.Input.Body
    ) async throws -> Operations.replaceContent.Output {
        try await replaceContent(Operations.replaceContent.Input(
            path: path,
            query: query,
            headers: headers,
            body: body
        ))
    }
}

/// Server URLs defined in the OpenAPI document.
public enum Servers {}
